---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: demoapp-common
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: demoapp
  validation: client

